-- Nikhat Middle School Digora — final normalized database schema
create extension if not exists pgcrypto;
create table if not exists schools(id uuid primary key default gen_random_uuid(),name text not null,dise_code text unique,address text,logo_url text,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists profiles(id uuid primary key references auth.users(id) on delete cascade,school_id uuid not null references schools(id),role text not null check(role in ('admin','principal','accountant','office','teacher','parent')),display_name text,employee_id text,student_id uuid,active boolean default true,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists academic_classes(id uuid primary key default gen_random_uuid(),school_id uuid not null references schools(id),session text not null,name text not null,section text not null default 'A',subjects jsonb default '[]'::jsonb,active boolean default true,unique(school_id,session,name,section));
create table if not exists students(id uuid primary key default gen_random_uuid(),school_id uuid not null references schools(id),admission_no text not null,roll_no text,name text not null,dob date,mother_name text,father_name text,guardian_name text,mobile text,samagra_id text,aadhaar text,class_id uuid references academic_classes(id),admission_date date,previous_school text,category text,status text default 'active',photo_url text,created_at timestamptz default now(),updated_at timestamptz default now(),unique(school_id,admission_no));
create table if not exists parent_contacts(id uuid primary key default gen_random_uuid(),school_id uuid not null references schools(id),student_id uuid not null references students(id),name text not null,relation text,mobile text,created_at timestamptz default now());
create table if not exists attendance(id uuid primary key default gen_random_uuid(),school_id uuid not null references schools(id),student_id uuid not null references students(id),attendance_date date not null,status text not null check(status in ('Present','Absent','Leave')),subject text,created_by uuid references profiles(id),created_at timestamptz default now(),updated_at timestamptz default now(),unique(student_id,attendance_date,subject));
create table if not exists exams(id uuid primary key default gen_random_uuid(),school_id uuid not null references schools(id),session text not null,name text not null,class_id uuid references academic_classes(id),exam_date date,created_by uuid references profiles(id),created_at timestamptz default now());
create table if not exists marks(id uuid primary key default gen_random_uuid(),school_id uuid not null references schools(id),exam_id uuid not null references exams(id),student_id uuid not null references students(id),subject text not null,score numeric(8,2) not null default 0,max_score numeric(8,2) not null default 100,created_by uuid references profiles(id),created_at timestamptz default now(),updated_at timestamptz default now(),unique(exam_id,student_id,subject));
create table if not exists fee_structures(id uuid primary key default gen_random_uuid(),school_id uuid not null references schools(id),session text not null,class_id uuid references academic_classes(id),fee_name text not null,amount numeric(12,2) not null default 0,active boolean default true,created_at timestamptz default now());
create table if not exists student_fee_accounts(id uuid primary key default gen_random_uuid(),school_id uuid not null references schools(id),student_id uuid not null references students(id),session text not null,opening_previous_due numeric(12,2) not null default 0,created_at timestamptz default now(),updated_at timestamptz default now(),unique(student_id,session));
create table if not exists fee_transactions(id uuid primary key default gen_random_uuid(),school_id uuid not null references schools(id),student_id uuid not null references students(id),account_id uuid references student_fee_accounts(id),receipt_no text not null,transaction_date date not null,amount numeric(12,2) not null check(amount>0),payment_mode text not null,note text,status text not null default 'posted' check(status in ('posted','void')),allocation_bucket text not null check(allocation_bucket in ('previous_due','current_fee')),created_by uuid references profiles(id),device_id text,created_at timestamptz default now(),updated_at timestamptz default now(),unique(school_id,receipt_no));
create table if not exists fee_allocations(id uuid primary key default gen_random_uuid(),transaction_id uuid not null references fee_transactions(id) on delete cascade,bucket text not null check(bucket in ('previous_due','current_fee')),amount numeric(12,2) not null check(amount>=0));
create table if not exists fee_voids(id uuid primary key default gen_random_uuid(),school_id uuid not null references schools(id),transaction_id uuid not null references fee_transactions(id),reason text,voided_by uuid references profiles(id),created_at timestamptz default now(),unique(transaction_id));
create table if not exists certificates(id uuid primary key default gen_random_uuid(),school_id uuid not null references schools(id),student_id uuid not null references students(id),certificate_no text not null,certificate_type text not null,certificate_date date not null,created_by uuid references profiles(id),created_at timestamptz default now(),unique(school_id,certificate_no));
create table if not exists timetable(id uuid primary key default gen_random_uuid(),school_id uuid not null references schools(id),class_id uuid references academic_classes(id),day_name text not null,period text not null,subject text,teacher_id uuid references profiles(id),room text,created_at timestamptz default now());
create table if not exists homework(id uuid primary key default gen_random_uuid(),school_id uuid not null references schools(id),class_id uuid references academic_classes(id),subject text,title text not null,description text,due_date date,published boolean default false,created_by uuid references profiles(id),created_at timestamptz default now());
create table if not exists notices(id uuid primary key default gen_random_uuid(),school_id uuid not null references schools(id),title text not null,body text not null,audience text default 'All',published_at timestamptz default now(),created_by uuid references profiles(id));
create table if not exists promotions(id uuid primary key default gen_random_uuid(),school_id uuid not null references schools(id),student_id uuid not null references students(id),from_session text,to_session text,result text not null,from_class_id uuid references academic_classes(id),to_class_id uuid references academic_classes(id),created_by uuid references profiles(id),created_at timestamptz default now());
create table if not exists audit_logs(id uuid primary key default gen_random_uuid(),school_id uuid not null references schools(id),actor_id uuid references profiles(id),action text not null,entity text not null,entity_id uuid,old_data jsonb,new_data jsonb,device_id text,created_at timestamptz default now());
create index if not exists fee_tx_student_date on fee_transactions(student_id,transaction_date desc);
create index if not exists fee_tx_school_date on fee_transactions(school_id,transaction_date desc);
create index if not exists attendance_student_date on attendance(student_id,attendance_date desc);
create index if not exists marks_student on marks(student_id);
-- IMPORTANT: enable RLS and add role/school policies in the Supabase SQL editor before production use.
-- Financial corrections are VOID + audit; never silently hard-delete a posted transaction.
